### ISSUE TITLE
Implement a max character for user input

### ISSUE THREAD

**Issue by christiansulaiman** [cse110-sp23-group1/Origami-Fortune-Teller#56]
Done to prevent the flaps from showing like a whole paragraph or something

**Comment by phentos** [comment]
~~does this conflict with the suggestion in #70 ? Capping the line length at some value still has more lines, then either use `lengthAdjust` to put the whole thing in the SVG or truncate it / number the sidebars / have the result pop up in full / etc -- so i don't think we necessarily need to limit total input so some specific number as this issue requires~~

original issue was erroneously referring to input box instead of sidebar entry
