### ISSUE TITLE
Code organization/smells need improvement

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/Origami-Fortune-Teller#86]
## Across all `.js`
- [ ] element getter functions are not used consistently
- [x] There is more core program behavior in the class files `SideBar.js` + `Origami.js` than in `main.js`
#### examples:
- `SideBar.js`: fortune input box, fortune storage, fortune retrieval, fortune save button
- `Origami.js`: sidebar reset button handler, titleHeader animation trigger

<br>

## In `SideBar.js`
- [x] The `DOMContentLoaded` handler is in `SideBar.js` instead of `main.js`
- [x] The `SideBar` class in `SideBar.js` is not used at all, making ~60 lines of the file dead code
#### possible paths to improvement:
- implement the class by incorporating the relevant globals into it
- delete the class and relocate the file's contents back to `main.js`
- delete the class and constrain file contents to sidebar items

<br>

## In `Origami.js`
- [ ] an excessive amount of constants are declared in `Origami.js`
#### possible paths to improvement:
- make use of transformation functions
- move origami constants to `fortunes.js` and rename the file to something like `config.js` (also update affected imports)
- make a new file specifically for origami constants

**Comment by adarsh249** [comment]
As important as this is, we simply do not have the time considering we have to make tests still and our two videos. There is a coding freeze by Sunday but the last thing we want is buggy code nearing our deadline because we tried to clean it up. In the e2e tests branch, I made a couple changes to clean it up a little bit with the utilities folder hosting two color functions (that we made unit tests for). But, we really need to focus on testing as it is 20% of the project grade as well as finishing up our documentation and video. We can do these things after Sunday's coding freeze, but people will have finals and other things to study for. I will make vote in Slack to see what direction people want to go in.

**Comment by phentos** [comment]
During the 6/6/23 lecture the professor stated a working app with code in disarray would be graded worse than a broken app with clean code. Thus, I feel that investing in the quality of our code rather than our code coverage makes more sense both from the perspective of the grade and the quality of our project. Further, not only is organizing our code extremely low risk for bug introduction and makes test implementation and documentation easier, I feel any bugs introduced would be worth it regardless, as the professor implied.

Lastly, we should observe that we have yet to do a thorough pass for cleanliness _at any point_. We know this is the case as the dead code I mentioned has been there for almost a month. As we have not maintained the quality of our code so far, I feel we would be lying to ourselves to think we will after release.
